Update cron schedule for new release

diff --git a/.github/workflows/cache.yml b/.github/workflows/cache.yml
--- a/.github/workflows/cache.yml
+++ b/.github/workflows/cache.yml
@@ -1,103 +1,95 @@
 name: Cache
-
 on:
-  workflow_dispatch:
+  workflow_dispatch: null
   schedule:
-    - cron: '0 0 * * *'
-
+    - cron: "0 0 * * * # Latest release:"
 jobs:
   build:
     runs-on: ubuntu-latest
-
     steps:
-    - name: Check for new release
-      uses: MoeKernel/github-script@v4
-      with:
-        script: |
-           const { data: releases } = await github.repos.listReleases({
-             owner: 'ZyCromerZ',
-             repo: 'Clang'
-           });
+      - name: Check for new release
+        uses: MoeKernel/github-script@v4
+        with:
+          script: >
+            const { data: releases } = await github.repos.listReleases({
+              owner: 'ZyCromerZ',
+              repo: 'Clang'
+            });
 
-           const latestRelease = releases[0];
-           console.log(`Latest release tag: ${latestRelease.tag_name}`);
-           
-           require('fs').writeFileSync('latest_release.txt', latestRelease.tag_name);
 
-    - name: Set cron schedule
-      uses: MoeKernel/set-cron-schedule-action@v2.0
-      with:
-        token: ${{ secrets.TOKEN_GITHUB }}
-        cron: |
-          0 0 * * * # Latest release: ${{ steps.check-for-new-release.outputs.latest_release }}
-        workflow: cache.yml
-        message: "Update cron schedule for new release"
+            const latestRelease = releases[0];
 
-    - name: Clone Repo Clang
-      uses: MoeKernel/github-repo-action@v3.1
-      with:
-        owner: 'MoeKernel'
-        repository: 'clang'
-        branch: 'main'
-        access-token: ${{ secrets.TOKEN_GITHUB }}
+            console.log(`Latest release tag: ${latestRelease.tag_name}`);
 
-    - name: Export Variables
-      working-directory: ./clang
-      run: |
-        echo "TOKEN_GITHUB=${{ secrets.TOKEN_GITHUB }}" >> .env
 
-    - name: Install Depends
-      working-directory: ./clang
-      run: |
-        pip install -r requirements.txt
+            require('fs').writeFileSync('latest_release.txt',
+            latestRelease.tag_name);
+      - name: Set cron schedule
+        uses: MoeKernel/set-cron-schedule-action@v2.0
+        with:
+          token: ${{ secrets.TOKEN_GITHUB }}
+          cron: >
+            0 0 * * * # Latest release: ${{
+            steps.check-for-new-release.outputs.latest_release }}
+          workflow: cache.yml
+          message: Update cron schedule for new release
+      - name: Clone Repo Clang
+        uses: MoeKernel/github-repo-action@v3.1
+        with:
+          owner: MoeKernel
+          repository: clang
+          branch: main
+          access-token: ${{ secrets.TOKEN_GITHUB }}
+      - name: Export Variables
+        working-directory: ./clang
+        run: |
+          echo "TOKEN_GITHUB=${{ secrets.TOKEN_GITHUB }}" >> .env
+      - name: Install Depends
+        working-directory: ./clang
+        run: |
+          pip install -r requirements.txt
+      - name: Check Clang Update
+        id: check-update
+        working-directory: ./clang
+        run: |
+          python3 update.py
+        continue-on-error: true
+      - name: Purge Cache
+        uses: MoeKernel/purge-cache@v2.1.0
+        with:
+          accessed: true
+          created: true
+          debug: true
+          max-age: 1
+          token: ${{ secrets.TOKEN_GITHUB }}
+      - name: Download Clang
+        if: steps.check-update.outcome == 'success'
+        working-directory: ./clang
+        run: |
+          chmod +x clang.sh
+          ./clang.sh
+      - name: Create Release to GitHub.
+        working-directory: ./clang
+        run: |
+          python3 create_release.py
+      - name: Setup GCC / GCC32 / Clang
+        run: |
+          TC_DIR="$HOME/tc/clang-19.0.0"
+          GCC_64_DIR="$HOME/tc/aarch64-linux-android-14.0"
+          GCC_32_DIR="$HOME/tc/arm-linux-androideabi-14.0"
 
-    - name: Check Clang Update
-      id: check-update
-      working-directory: ./clang
-      run: |
-        python3 update.py
-      continue-on-error: true
+          if ! [ -d "${GCC_64_DIR}" ]; then
+              echo "gcc not found! Cloning to ${GCC_64_DIR}..."
+              git clone --depth=1 -b 14 https://github.com/ZyCromerZ/aarch64-zyc-linux-gnu ${GCC_64_DIR}
+          fi
 
-    - name: Purge Cache
-      uses: MoeKernel/purge-cache@v2.1.0
-      with:
-        accessed: true
-        created: true
-        debug: true
-        max-age: 1
-        token: ${{ secrets.TOKEN_GITHUB }}
-
-    - name: Download Clang
-      if: steps.check-update.outcome == 'success'
-      working-directory: ./clang
-      run: |
-        chmod +x clang.sh
-        ./clang.sh
-
-    - name: Create Release to GitHub.
-      working-directory: ./clang
-      run: |
-        python3 create_release.py
-
-    - name: Setup GCC / GCC32 / Clang
-      run: |
-        TC_DIR="$HOME/tc/clang-19.0.0"
-        GCC_64_DIR="$HOME/tc/aarch64-linux-android-14.0"
-        GCC_32_DIR="$HOME/tc/arm-linux-androideabi-14.0"
-
-        if ! [ -d "${GCC_64_DIR}" ]; then
-            echo "gcc not found! Cloning to ${GCC_64_DIR}..."
-            git clone --depth=1 -b 14 https://github.com/ZyCromerZ/aarch64-zyc-linux-gnu ${GCC_64_DIR}
-        fi
-
-        if ! [ -d "${GCC_32_DIR}" ]; then
-            echo "gcc_32 not found! Cloning to ${GCC_32_DIR}..."
-            git clone --depth=1 -b 14 https://github.com/ZyCromerZ/arm-zyc-linux-gnueabi ${GCC_32_DIR}
-        fi
-
-    - name: Cache Create
-      id: tc-cache
-      uses: MoeKernel/cache/save@v3
-      with:
-        path: /home/runner/tc
-        key: ${{ runner.os }}-tc
+          if ! [ -d "${GCC_32_DIR}" ]; then
+              echo "gcc_32 not found! Cloning to ${GCC_32_DIR}..."
+              git clone --depth=1 -b 14 https://github.com/ZyCromerZ/arm-zyc-linux-gnueabi ${GCC_32_DIR}
+          fi
+      - name: Cache Create
+        id: tc-cache
+        uses: MoeKernel/cache/save@v3
+        with:
+          path: /home/runner/tc
+          key: ${{ runner.os }}-tc
