Update toolchan.yml

diff --git a/.github/workflows/toolchan.yml b/.github/workflows/toolchan.yml
--- a/.github/workflows/toolchan.yml
+++ b/.github/workflows/toolchan.yml
@@ -25,15 +25,13 @@ jobs:
         run: |
           pip install -r requirements.txt
 
-      - name: Download Clang
-        working-directory: ./clang
-        run: |
-          chmod +x toolchain.sh
-          ./toolchain.sh
-
       - name: Setup Clang
         run: |
           TC_DIR="$HOME/tc/clang-17.0.0"
+          if ! [ -d "${TC_DIR}" ]; then
+              echo "Clang not found! Cloning to ${TC_DIR}..."
+              git clone --depth=1 https://gitlab.com/moehacker/clang-r487747.git ${TC_DIR}
+          fi
 
       - name: Cache Create
         id: tc-toolchain
